version: '3'

services:
  tasker-app:
    container_name: tasker-app
    build: ./tasker-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tasker?autoReconnect=true&useSSL=false
    ports:
      - 4040:4040
    depends_on:
      - tasker-db

  tasker-web:
    container_name: tasker-web
    restart: always
    build: ./tasker-web/main
    ports:
      - 4200:4200
