version: '3'

services:
  tasker-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gvele
      MYSQL_DATABASE: tasker
      MYSQL_USER: gvele
      MYSQL_PASSWORD: gvele
    ports:
      - 3307:3306

  tasker-app:
    container_name: tasker-app
    build: ./tasker-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tasker-db:3306/tasker?autoReconnect=true&useSSL=false
    ports:
      - 4040:4040
    depends_on:
      - tasker-db

  tasker-web:
    container_name: tasker-web
    restart: always
    build: ./tasker-web/main
    ports:
      - 4200:4200
